### ISSUE TITLE
more textual files are also infected

### ISSUE THREAD

**Issue by AdonisGe** [Guiomuh/WP_Redirect_Botnet_Cleaner#2]
In my case, the json files, js.map files,  js.template are also infected.

wp-content/themes/v6.1.2/includes/lib/inc/redux/extensions/vendorsupport/vendor_support/vendor/select3/select3_locale_en.js.template
wp-content/plugins/wp-rocket/assets/js/wpr-admin.js.map
wp-content/plugins/wp-rocket/assets/js/lazyload/12.0/lazyload.min.js.map
wp-content/plugins/wp-rocket/assets/js/lazyload/11.0.6/lazyload.min.js.map
wp-content/plugins/download-manager/assets/bootstrap/js/bootstrap.bundle.min.js.map
wp-content/plugins/download-manager/assets/bootstrap/js/bootstrap.js.map
wp-content/plugins/download-manager/assets/bootstrap/js/bootstrap.bundle.js.map
wp-content/plugins/download-manager/assets/bootstrap/js/bootstrap.min.js.map
wp-content/plugins/woocommerce/packages/woocommerce-blocks/assets/js/components/product-preview/test/__snapshots__/index.js.snap
wp-content/plugins/woocommerce/packages/woocommerce-blocks/assets/js/base/components/label/test/__snapshots__/index.js.snap
wp-content/plugins/fusion-builder/inc/lib/inc/redux/extensions/vendorsupport/vendor_support/vendor/select3/select3_locale_en.js.template

**Comment by AdonisGe** [comment]
They will modify database wp_option table,  remember to correct the site_url and home_url

**Comment by Guiomuh** [comment]
Thanks for the info I'll add this to the scripts very soon :)

**Comment by Guiomuh** [comment]
It's now fixed ! 
The malware targets "\*.js\*" files and not only "*.js". 
That's why .json .js.map are also infected
