### ISSUE TITLE
0 infected files found, site still broken

### ISSUE THREAD

**Issue by Zibidibodel** [Guiomuh/WP_Redirect_Botnet_Cleaner#3]
I've run all of this on my server through SSH and it's now finding 0 infected files, 0 tmp/log files, no infected records in the database, but even after clearing caches when I visit the site it still points towards letsmakeparty3.gu

Any idea what could have been missed?

**Comment by Guiomuh** [comment]
I've improved the detection script retry maybe you'll find some new payloads 
You can also check manually the site_url and home_url values in the database's wp_options table. (https://wordpress.org/support/article/changing-the-site-url/#changing-the-url-directly-in-the-database)
These values are modified sometimes by the virus this fix I'll be added soon in the scripts

**Comment by Zibidibodel** [comment]
Thanks! The db entry is what got it. Weird, but that resolved it. Thanks for all your hard work!
