### ISSUE TITLE
Different table names + put ' ' around siteurl in the SQL query

### ISSUE THREAD

**Issue by davext** [Guiomuh/WP_Redirect_Botnet_Cleaner#4]
First thank you for providing this!

1.  rename wp_config table to wp_options
I did the work manually because my wp_config is called wp_options apparently. So I looked online for Wordpress documentation and I found this https://codex.wordpress.org/Database_Description#Table:_wp_options

I think it's wp_options in most/recent installations maybe?

2. surround "siteurl" with single quotes in the SQL query for your python files to be able to find it. The python files couldn't find the row where the table had siteurl. Worked right away once i added single quotes :)

Best,
David

**Comment by Guiomuh** [comment]
Hi thanks for your return ! In fact the table on my test WordPress was renamed by a plugin..
So I fixed that and to make the script more reliable I added a search of this table in case a DB Table Prefix is used :)
